name: duwcm
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.12.2
  - contextily
  - dynaconf
  - geopandas
  - geopandas-base
  - geopy
  - hdf5
  - imageio
  - jupyter
  - matplotlib
  - ncurses
  - numpy
  - pandas
  - pip
  - pylint
  - pytables
  - scipy
  - seaborn
  - setuptools
  - shapely
  - sqlalchemy
  - sqlite
  - tomli
  - tomlkit
  - tqdm
  - typing-extensions
