name: duwcm
channels:
  - defaults
  - conda-forge
dependencies:
  - astroid=3.2.4=py312h81bd7bf_0
  - blas=1.0=openblas
  - blosc=1.21.6=h5499902_0
  - bottleneck=1.3.7=py312ha86b861_0
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.33.1=hd74edd7_0
  - c-blosc2=2.15.1=h5063078_0
  - ca-certificates=2024.7.4=hf0a4a13_0
  - certifi=2024.7.4=py312hca03da5_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.2.1=py312h0fef576_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dill=0.3.8=pyhd8ed1ab_0
  - dynaconf=3.2.6=pyhd8ed1ab_0
  - expat=2.6.2=h313beb8_0
  - fonttools=4.53.1=py312h7e5086c_0
  - freetype=2.12.1=hadb7bae_2
  - greenlet=3.0.1=py312h313beb8_0
  - hdf5=1.14.3=nompi_hec07895_105
  - isort=5.13.2=pyhd8ed1ab_0
  - kiwisolver=1.4.5=py312h389731b_1
  - krb5=1.21.3=h237132a_0
  - lcms2=2.16=ha0e7c42_0
  - lerc=4.0.0=h9a09cb3_0
  - libaec=1.1.3=hebf3989_0
  - libblas=3.9.0=16_osxarm64_openblas
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcurl=8.9.1=hfd8ffcc_0
  - libcxx=18.1.8=h167917d_2
  - libdeflate=1.20=h93a5062_0
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libexpat=2.6.2=hebf3989_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=16_osxarm64_openblas
  - libnghttp2=1.58.0=ha4dd798_1
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.43=h091b4b1_0
  - libsqlite=3.45.2=h091b4b1_0
  - libssh2=1.11.0=h7a5bd25_0
  - libtiff=4.6.0=h07db509_3
  - libwebp-base=1.4.0=h93a5062_0
  - libxcb=1.16=hf2054a2_0
  - libzlib=1.3.1=hfb2fe0b_1
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - matplotlib=3.9.1=py312h1f38498_1
  - matplotlib-base=3.9.1=py312h32d6e5a_1
  - mccabe=0.7.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=h313beb8_0
  - numexpr=2.8.7=py312h0f3ea24_0
  - numpy=1.26.4=py312h7f4fdc5_0
  - numpy-base=1.26.4=py312he047099_0
  - openjpeg=2.5.2=h9f1df11_0
  - openssl=3.3.1=hfb2fe0b_2
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py312hd77ebd4_0
  - pillow=10.4.0=py312h39b1d8d_0
  - pip=24.0=py312hca03da5_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - pthread-stubs=0.4=h27ca646_1001
  - py-cpuinfo=9.0.0=py312hca03da5_0
  - pylint=3.2.6=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pytables=3.10.1=py312h36a7e55_1
  - python=3.12.2=hdf0ec26_0_cpython
  - python-dateutil=2.9.0post0=py312hca03da5_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.12=4_cp312
  - pytz=2024.1=py312hca03da5_0
  - qhull=2020.2=h420ef59_5
  - readline=8.2=h1a28f6b_0
  - scipy=1.14.0=py312h14ffa8f_1
  - setuptools=69.5.1=py312hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h313beb8_0
  - sqlalchemy=2.0.32=py312h7e5086c_0
  - sqlite=3.45.2=hf2abe2d_0
  - tk=8.6.13=h5083fa2_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.13.0=pyha770c72_0
  - tornado=6.4.1=py312h7e5086c_0
  - tqdm=4.66.5=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.43.0=py312hca03da5_0
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.4.6=h80987f9_1
  - zlib=1.3.1=hfb2fe0b_1
  - zlib-ng=2.2.1=h00cdb27_0
  - zstd=1.5.6=hb46c0d2_0
  - pip:
      - appnope==0.1.4
      - asttokens==2.4.1
      - attrs==24.2.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - charset-normalizer==3.3.2
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docopt==0.6.2
      - executing==2.0.1
      - fastjsonschema==2.20.0
      - idna==3.8
      - ipython==8.12.3
      - jedi==0.19.1
      - jinja2==3.1.4
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyterlab-pygments==0.3.0
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pipreqs==0.5.0
      - prompt-toolkit==3.0.47
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.18.0
      - pyzmq==26.2.0
      - referencing==0.35.1
      - requests==2.32.3
      - rpds-py==0.20.0
      - simpledbf==0.2.6
      - soupsieve==2.6
      - stack-data==0.6.3
      - tinycss2==1.3.0
      - traitlets==5.14.3
      - urllib3==2.2.2
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - yarg==0.1.9
