name: duwcm
channels:
  - defaults
  - conda-forge
dependencies:
  - affine=2.3.0=pyhd3eb1b0_0
  - astroid=3.2.4=py312h81bd7bf_0
  - aws-c-auth=0.7.22=h27bc0eb_5
  - aws-c-cal=0.6.15=h5db4892_0
  - aws-c-common=0.9.19=h99b78c6_0
  - aws-c-compression=0.2.18=h5db4892_6
  - aws-c-event-stream=0.4.2=h4de9e5c_13
  - aws-c-http=0.8.2=h2c662d3_2
  - aws-c-io=0.14.9=h8709d7d_2
  - aws-c-mqtt=0.10.4=h5fc5ab5_6
  - aws-c-s3=0.5.10=h48f01f6_3
  - aws-c-sdkutils=0.1.16=h5db4892_2
  - aws-checksums=0.1.18=h5db4892_6
  - aws-crt-cpp=0.26.10=h9d69022_4
  - aws-sdk-cpp=1.11.329=hfa7c70e_4
  - azure-core-cpp=1.11.1=he231e37_1
  - azure-identity-cpp=1.6.0=hd1853d3_1
  - azure-storage-blobs-cpp=12.10.0=h2ffa867_1
  - azure-storage-common-cpp=12.5.0=h09a5875_4
  - blas=1.0=openblas
  - blosc=1.21.6=h5499902_0
  - bottleneck=1.3.7=py312ha86b861_0
  - branca=0.6.0=py312hca03da5_0
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - brotli-python=1.0.9=py312h313beb8_8
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.33.1=hd74edd7_0
  - c-blosc2=2.15.1=h5063078_0
  - ca-certificates=2024.7.4=hf0a4a13_0
  - cairo=1.18.0=hc6c324b_2
  - certifi=2024.8.30=py312hca03da5_0
  - cfitsio=4.4.0=h808cd33_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py312hca03da5_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contextily=1.6.2=pyhd8ed1ab_0
  - contourpy=1.2.1=py312h0fef576_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dill=0.3.8=pyhd8ed1ab_0
  - dynaconf=3.2.6=pyhd8ed1ab_0
  - expat=2.6.2=h313beb8_0
  - fiona=1.9.6=py312h831b459_2
  - fmt=10.2.1=h2ffa867_0
  - folium=0.14.0=py312hca03da5_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h82840c6_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.53.1=py312h7e5086c_0
  - freetype=2.12.1=hadb7bae_2
  - freexl=2.0.0=ha3de405_0
  - gdal=3.8.5=py312hb48d578_1
  - geographiclib=2.0=py312hca03da5_0
  - geopandas=0.14.2=py312hca03da5_0
  - geopandas-base=0.14.2=py312hca03da5_0
  - geopy=2.4.1=py312hca03da5_0
  - geos=3.12.1=h965bd2d_0
  - geotiff=1.7.3=h7e5fb84_1
  - gettext=0.22.5=h8414b35_3
  - gettext-tools=0.22.5=h8414b35_3
  - giflib=5.2.2=h93a5062_0
  - greenlet=3.0.1=py312h313beb8_0
  - hdf4=4.2.15=h2ee6834_7
  - hdf5=1.14.3=nompi_hec07895_105
  - icu=73.2=hc8870d7_0
  - isort=5.13.2=pyhd8ed1ab_0
  - jinja2=3.1.4=py312hca03da5_0
  - joblib=1.4.2=py312hca03da5_0
  - json-c=0.17=he54c16a_1
  - kealib=1.5.3=h8edbb62_2
  - kiwisolver=1.4.5=py312h389731b_1
  - krb5=1.21.3=h237132a_0
  - lcms2=2.16=ha0e7c42_0
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20240116.2=cxx17_h313beb8_0
  - libaec=1.1.3=hebf3989_0
  - libarchive=3.7.4=h83d404f_0
  - libasprintf=0.22.5=h8414b35_3
  - libasprintf-devel=0.22.5=h8414b35_3
  - libblas=3.9.0=16_osxarm64_openblas
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcrc32c=1.1.2=hc377ac9_0
  - libcurl=8.9.1=hfd8ffcc_0
  - libcxx=18.1.8=h167917d_2
  - libdeflate=1.20=h93a5062_0
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libexpat=2.6.2=hebf3989_0
  - libffi=3.4.4=hca03da5_1
  - libgdal=3.8.5=hfb644ca_1
  - libgettextpo=0.22.5=h8414b35_3
  - libgettextpo-devel=0.22.5=h8414b35_3
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - libglib=2.80.2=h535f939_0
  - libgoogle-cloud=2.24.0=hfe08963_0
  - libgoogle-cloud-storage=2.24.0=h3fa5b87_0
  - libgrpc=1.62.2=h9c18a4f_0
  - libiconv=1.17=h0d3ecfb_2
  - libintl=0.22.5=h8414b35_3
  - libintl-devel=0.22.5=h8414b35_3
  - libjpeg-turbo=3.0.0=hb547adb_1
  - libkml=1.3.0=he250239_1021
  - liblapack=3.9.0=16_osxarm64_openblas
  - libnetcdf=4.9.2=nompi_he469be0_114
  - libnghttp2=1.58.0=ha4dd798_1
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.43=h091b4b1_0
  - libpq=16.4=h671472c_1
  - libprotobuf=4.25.3=hbfab5d5_0
  - libre2-11=2023.09.01=h7b2c953_2
  - librttopo=1.1.0=hc8f776e_15
  - libspatialindex=1.9.3=hc377ac9_0
  - libspatialite=5.1.0=h77c30ab_5
  - libsqlite=3.45.2=h091b4b1_0
  - libssh2=1.11.0=h7a5bd25_0
  - libtiff=4.6.0=h07db509_3
  - libwebp-base=1.4.0=h93a5062_0
  - libxcb=1.16=hf2054a2_0
  - libxml2=2.12.7=h9a80f22_3
  - libzip=1.10.1=ha0bc3c6_3
  - libzlib=1.3.1=hfb2fe0b_1
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - lzo=2.10=h1a28f6b_2
  - mapclassify=2.5.0=py312hca03da5_0
  - matplotlib=3.9.1=py312h1f38498_1
  - matplotlib-base=3.9.1=py312h32d6e5a_1
  - matplotlib-scalebar=0.8.1=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd8ed1ab_0
  - mercantile=1.2.1=pyhd8ed1ab_0
  - minizip=4.0.7=h27ee973_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=h313beb8_0
  - networkx=3.3=py312hca03da5_0
  - nspr=4.35=h313beb8_0
  - nss=3.98=h5ce2875_0
  - numexpr=2.8.7=py312h0f3ea24_0
  - numpy=1.26.4=py312h7f4fdc5_0
  - numpy-base=1.26.4=py312he047099_0
  - openjpeg=2.5.2=h9f1df11_0
  - openssl=3.3.1=hfb2fe0b_2
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py312hd77ebd4_0
  - patsy=0.5.6=py312hca03da5_0
  - pcre2=10.43=h26f9a81_0
  - pillow=10.4.0=py312h39b1d8d_0
  - pip=24.0=py312hca03da5_0
  - pixman=0.43.4=hebf3989_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - poppler=24.03.0=h896e6cb_0
  - poppler-data=0.4.11=hca03da5_1
  - postgresql=16.4=ha29bbc8_1
  - proj=9.4.0=h52fb9d0_0
  - pthread-stubs=0.4=h27ca646_1001
  - py-cpuinfo=9.0.0=py312hca03da5_0
  - pylint=3.2.6=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyproj=3.6.1=py312h64656f7_7
  - pysocks=1.7.1=py312hca03da5_0
  - pytables=3.10.1=py312h36a7e55_1
  - python=3.12.2=hdf0ec26_0_cpython
  - python-dateutil=2.9.0post0=py312hca03da5_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.12=4_cp312
  - pytz=2024.1=py312hca03da5_0
  - qhull=2020.2=h420ef59_5
  - rasterio=1.3.10=py312h90d5f4c_2
  - re2=2023.09.01=h4cba328_2
  - readline=8.2=h1a28f6b_0
  - requests=2.32.3=py312hca03da5_0
  - rtree=1.0.1=py312hca03da5_0
  - scikit-learn=1.5.1=py312hd77ebd4_0
  - scipy=1.14.0=py312h14ffa8f_1
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - setuptools=69.5.1=py312hca03da5_0
  - shapely=2.0.4=py312hbea5422_1
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h313beb8_0
  - snuggs=1.4.7=pyhd3eb1b0_0
  - spdlog=1.13.0=h5fcca99_0
  - sqlalchemy=2.0.32=py312h7e5086c_0
  - sqlite=3.45.2=hf2abe2d_0
  - statsmodels=0.14.2=py312ha86b861_0
  - threadpoolctl=3.5.0=py312h989b03a_0
  - tiledb=2.22.0=hcda1485_6
  - tk=8.6.13=h5083fa2_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.13.0=pyha770c72_0
  - tornado=6.4.1=py312h7e5086c_0
  - tqdm=4.66.5=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzcode=2024b=hd74edd7_0
  - tzdata=2024a=h04d1e81_0
  - uriparser=0.9.8=h00cdb27_0
  - urllib3=2.2.2=py312hca03da5_0
  - wheel=0.43.0=py312hca03da5_0
  - xerces-c=3.2.5=hf393695_0
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xyzservices=2022.9.0=py312hca03da5_1
  - xz=5.4.6=h80987f9_1
  - zlib=1.3.1=hfb2fe0b_1
  - zlib-ng=2.2.1=h00cdb27_0
  - zstd=1.5.6=hb46c0d2_0
  - pip:
      - appnope==0.1.4
      - asttokens==2.4.1
      - attrs==24.2.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docopt==0.6.2
      - executing==2.0.1
      - fastjsonschema==2.20.0
      - idna==3.8
      - ipython==8.12.3
      - jedi==0.19.1
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyterlab-pygments==0.3.0
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pipreqs==0.5.0
      - prompt-toolkit==3.0.47
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.18.0
      - pyzmq==26.2.0
      - referencing==0.35.1
      - rpds-py==0.20.0
      - simpledbf==0.2.6
      - soupsieve==2.6
      - stack-data==0.6.3
      - tinycss2==1.3.0
      - traitlets==5.14.3
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - yarg==0.1.9
