name: duwcm
channels:
  - defaults
  - conda-forge
dependencies:
  - contextily=1.6.2
  - geopandas=0.14.2
  - geopandas-base=0.14.2
  - geopy=2.4.1
  - hdf5=1.14.3
  - imageio=2.35.1
  - matplotlib=3.9.1
  - ncurses=6.4
  - numpy=1.26.4
  - pandas=2.2.2
  - pip=24.0
  - pylint=3.2.6
    pytables=3.10.1
  - python=3.12.2
  - scipy=1.14.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=69.5.1
  - shapely=2.0.4
  - sqlalchemy=2.0.32
  - sqlite=3.45.2
  - tomli=2.0.1
  - tomlkit=0.13.0
  - tqdm=4.66.5
  - typing-extensions=4.12.2
  - pip:
      - ipython==8.12.3
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyterlab-pygments==0.3.0
      - pipreqs==0.5.0
