[default]
input_directory = 'input/'
geodata_directory = 'input/geodata'

# Grid settings
[default.grid]
cell_size = 200  # meters
direction = 6  # number of neighbors (4, 6, or 8)
#selected_cells = [670, 671, 672, 706, 707, 708, 709, 710, 742, 743, 744, 745, 746, 780, 781, 782, 817, 818, 819]  # List of cells to simulate

# File paths
[default.files]
urban_beats_file = 'Fehraltorf_HexagonsNS_200m_Blocks.dbf'
calibration_file = 's0param.csv'
alternative_water_file = 'alternative0.csv'
groundwater_file = 'gw0m_IDW2Hex200fromswbi.csv'
soil_file = 'in_soilparameter_new.csv'
et_file = 'in_etparameter.csv'
climate_file = 'forcing.csv'
open_water_file = 'forcingOW.csv'
reuse_settings_file = 'settingreuse.csv'
demand_file = 'profile_percentage.csv'
geo_file = 'hex_geo.gpkg'

# Background shapefile
background_shapefile = 'Boundary_LV95.shp'

# Feature shapefiles
feature_shapefiles = [
    'Rivers_LV95.shp',
    'Buildings_LV95.shp',
    'CH_ARE_Bauzonen_LV95.shp'
]

# Simulation settings
[default.simulation]
start_year = 2018
end_year = 2018
time_step = 1
init_method = "cyclic"  # or "ensemble"
spinup_cycles = 10
#resample_frequency = 'W'  # 'W' for weekly, 'M' for monthly, '2W' for bi-weekly, etc.


# Output settings
[default.output]
output_directory = 'results'
detailed_results = true
crs = 'EPSG:2056'

# Plotting settings
[default.plot]
modules = []#['roof', 'groundwater', 'vadose']
variables = []#['storage', 'evaporation', 'water_level', 'moisture']
cells = []#[43, 120]  # List of cell IDs to plot
